cursor #e0e2e7
cursor_text_color #c0c7d0

foreground            #e0e2e7
background            #101417
selection_foreground  #183345
selection_background  #afcae1
url_color             #8bceff

color0   #101417
color1   #ff729e
color2   #7fff8f
color3   #fff772
color4   #6ebaf2
color5   #134c76
color6   #8bceff
color7   #eff8ff
color8   #99a0a5
color9   #ff9fbc
color10  #a5ffb0
color11  #fff9a5
color12  #9cd5ff
color13  #addcff
color14  #cae8ff
color15  #f8fcff
