cursor #e5e1e3
cursor_text_color #c9c5cd

foreground            #e5e1e3
background            #141315
selection_foreground  #312f38
selection_background  #c9c5cf
url_color             #c8c3dc

color0   #141315
color1   #fd718f
color2   #6edc84
color3   #ffd972
color4   #bab4d1
color5   #545065
color6   #c8c3dc
color7   #dbd9e7
color8   #86848f
color9   #ff9fb4
color10  #a5ffb7
color11  #ffe7a5
color12  #dfdaf2
color13  #eeeaff
color14  #f4f1ff
color15  #f9f8ff
