cursor #e3e2e5
cursor_text_color #c3c7cf

foreground            #e3e2e5
background            #121316
selection_foreground  #25313f
selection_background  #bbc7da
url_color             #a8c9f3

color0   #121316
color1   #ff729b
color2   #79f38a
color3   #fff772
color4   #91b6e6
color5   #304c70
color6   #a8c9f3
color7   #eff6ff
color8   #92979d
color9   #ff9fbb
color10  #a5ffb2
color11  #fffaa5
color12  #bcd9ff
color13  #c7e0ff
color14  #dbebff
color15  #f8fbff
