[colors.primary]
background = '#101417'
foreground = '#e0e3e8'

[colors.selection]
text = '#e0e3e8'
background = '#004b6f'

[colors.cursor]
text = '#101417'
cursor = '#95cdf7'

[colors.normal]
black   = '#101417'
red     = '#ff729e'
green   = '#7bf78a'
yellow  = '#fff772'
blue    = '#7abaea'
magenta = '#1f4e72'
cyan    = '#95cdf7'
white   = '#eff8ff'

[colors.bright]
black   = '#949ba0'
red     = '#ff9fbc'
green   = '#a5ffb0'
yellow  = '#fff9a5'
blue    = '#a9daff'
magenta = '#b8e0ff'
cyan    = '#d1ebff'
white   = '#f8fcff'
