[colors.primary]
background = '#101417'
foreground = '#e0e2e7'

[colors.selection]
text = '#e0e2e7'
background = '#277cad'

[colors.cursor]
text = '#101417'
cursor = '#8bceff'

[colors.normal]
black   = '#101417'
red     = '#ff729e'
green   = '#7fff8f'
yellow  = '#fff772'
blue    = '#6ebaf2'
magenta = '#134c76'
cyan    = '#8bceff'
white   = '#eff8ff'

[colors.bright]
black   = '#99a0a5'
red     = '#ff9fbc'
green   = '#a5ffb0'
yellow  = '#fff9a5'
blue    = '#9cd5ff'
magenta = '#addcff'
cyan    = '#cae8ff'
white   = '#f8fcff'
