[colors.primary]
background = '#141315'
foreground = '#e5e1e3'

[colors.selection]
text = '#e5e1e3'
background = '#636075'

[colors.cursor]
text = '#141315'
cursor = '#c8c3dc'

[colors.normal]
black   = '#141315'
red     = '#fd718f'
green   = '#6edc84'
yellow  = '#ffd972'
blue    = '#bab4d1'
magenta = '#545065'
cyan    = '#c8c3dc'
white   = '#dbd9e7'

[colors.bright]
black   = '#86848f'
red     = '#ff9fb4'
green   = '#a5ffb7'
yellow  = '#ffe7a5'
blue    = '#dfdaf2'
magenta = '#eeeaff'
cyan    = '#f4f1ff'
white   = '#f9f8ff'
